# For local development/live edit:
# python3 -m venv .venv (required only once)
# source .venv/bin/activate
# pip install -r .github/workflows/mkdocs-requirements.txt
# ./scripts/copy_docs_files.sh
# mkdocs serve
#
# ℹ️ NOTE: Deployment is done via `mike` for versioned site using GitHub Actions
#          For manual deployment, use `./scripts/deploy_metro_docs_site.sh`

site_name: Metro
repo_name: Metro
repo_url: https://github.com/ZacSweers/metro
site_url: https://zacsweers.github.io/metro/
site_description: "A multiplatform dependency injection framework for Kotlin"
site_author: Zac Sweers
remote_branch: gh-pages

copyright: 'Copyright &copy; 2025 Zac Sweers'

theme:
  name: 'material'
  favicon: site-assets/img/favicon.ico
  logo: site-assets/img/metro-icon.svg
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Inter'
    code: 'Fira Code'
  features:
    - content.code.copy
    - content.code.select
  # Custom dir for theme overrides (eg. custom 404 page)
  # - https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: 'docs/site-assets/overrides'

plugins:
  # Social plugin for delightful card previews on social media
  # https://squidfunk.github.io/mkdocs-material/plugins/social/
  - social
  - search
  # Versioned Metro docs site for each release
  # https://github.com/jimporter/mike
  - mike
  # https://github.com/sondregronas/mkdocs-callouts
  - callouts

#extra_css:
#  - 'css/app.css'

extra:
  version:
    provider: mike

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - attr_list
  - md_in_html
  - nl2br

nav:
  - 'Introduction': index.md
  - 'Overview':
    - 'Features': features.md
    - 'Differences': differences.md
  - 'Installation': installation.md
  - 'Usage':
      - 'Dependency Graphs': dependency-graphs.md
      - 'Provides': provides.md
      - 'Injection Types': injection-types.md
      - 'Scopes': scopes.md
      - 'Metro Intrinsics': metro-intrinsics.md
      - 'Bindings': bindings.md
      - 'Aggregation (aka "Anvil")': aggregation.md
      - 'Multiplatform': multiplatform.md
      - 'Validation & Error Reporting': validation-and-error-reporting.md
      - 'Interop': interop.md
      - 'Generating Custom Metro Code': generating-metro-code.md
  - 'Performance': performance.md
  - 'Debugging': debugging.md
  - 'Compatibility': compatibility.md
  - 'Adoption Strategies': adoption.md
  - 'FAQ': faq.md
  - 'Samples': samples.md
  - 'API': api/index.html
  - 'Discussions ⏏': https://github.com/ZacSweers/metro/discussions
  - 'Change Log': changelog.md
  - 'Contributing': contributing.md
  - 'CoC': code-of-conduct.md
